// <auto-generated />
namespace TesoroQR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class InitPrimero : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitPrimero));
        
        string IMigrationMetadata.Id
        {
            get { return "201406251556042_InitPrimero"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
